---
stages:
  - lint

golangci-lint:
  stage: lint
  image: golangci/golangci-lint:v2.12.2
  script:
    # Runs .golangci.yml linter configuration file
    - golangci-lint run ./...
  allow_failure: false
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/golangci-lint

hadolint:
  stage: lint
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint Dockerfile
  allow_failure: false

yaml-lint:
  stage: lint
  image: python:alpine
  script:
    - apk add --no-cache yamllint
    - yamllint .
  allow_failure: true

docker-compose:
  stage: lint
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker compose config -q
  allow_failure: false
