# SonarCloud Identification Keys
sonar.projectKey=yerdaulet.zhumabay_pizza-golang-deletion_scheduled-83574917
sonar.organization=yerdaulet-zhumabay
sonar.projectName=pizza-golang-deletion_scheduled

# Production Source Code Management
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,tmp/**,.cache/**,bin/**
sonar.sourceEncoding=UTF-8

# Test Code & Coverage Reporting
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**
sonar.go.coverage.reportPaths=coverage.out
